### ISSUE TITLE
Phaser List View does not work on IE10, android stock browser

### ISSUE THREAD

**Issue by ShadyChan93** [mattcolman/phaser-list-view#12]
I implemented the list view for my game scoreboard, tested it with chrome in redmi 1s and desktop works perfectly, but it wont even start the specific scene that use list view when it being tested on stock browser. Is it an unresolved issue or you can please give me some guide? btw, i using the script tag to implement

**Comment by mattcolman** [comment]
Sorry I'm not sure. I am unable to test it on IE10 or android stock browser. Does the Phaser example page work on IE10 or android stock browser? http://mattcolman.com/labs/phaser-list-view/index.html

**Comment by mattcolman** [comment]
This is pretty out of date, no one else has reported this issue, closing.
