### ISSUE TITLE
Add TypeScript bindings

### ISSUE THREAD

**Issue by haspide** [mattcolman/phaser-list-view#13]
Would it be possible to add TypeScript bindings so this library is usable with TypeScript Phaser projects?

**Comment by mattcolman** [comment]
You're welcome to submit a Pull Request and I'll happily merge it. I don't use typescript and have never written typescript bindings before.

**Comment by drewsilcock** [comment]
Haven't yet tested this, but here's a .d.ts. I will comment further if this works/doesn't work/needs modification once I've actually got the plugin working.

Edit: Changed options to have optional properties, changed `export`s to `declare`s.

Edit2: Typings file was getting a bit unwieldy for a comment like this. I've moved it to its own repository, so you can fork and improve it (please!) and use it via Typings with ease. I *am* using this, so I can confirm that is *does* work.

Link: [drewsilcock/phaser-list-view-typings](https://github.com/drewsilcock/phaser-list-view-typings).

**Comment by mattcolman** [comment]
Cool thanks @drewsilcock ! Nice work!
